name: sound-transfer
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - tqdm
  - diffusers
  - transformers
  - pydub
  - scikit-learn
  - matplotlib
  - pip
  - pip:
    - laion-clap