name: sound-transfer
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - jupyter
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - tqdm
  - diffusers
  - transformers